### ISSUE TITLE
height of khala parachain is zero when running in testnet

### ISSUE THREAD

**Issue by sindhu0820** [HugoByte/dive-core#108]
## Overview
height of khala parachain is zero when running in testnet

## Steps to Reproduce
1. run khala parachain in testnet
2. command: ./dive chain kusama -p khala -n testnet

## Expected Behavior
block height should be incrementing

## Actual Behavior
no increment in block height

**Comment by hemz10** [comment]
As mentioned in the [report](https://docs.google.com/spreadsheets/d/1-3DYhOcAjq1GYoBvc8iTN-xhYIOStKDKA6A3eVA0E40/edit#gid=0) since Khala testnet is not active closing this issue as deferred
