### ISSUE TITLE
height of manta parachain is zero when running in testnet

### ISSUE THREAD

**Issue by sindhu0820** [HugoByte/dive-core#112]
## Overview
height of manta parachain is zero when running in testnet

## Steps to Reproduce
1. run manta parachain in testnet
2. command: ./dive chain polkadot -p manta -n testnet

## Expected Behavior
block height should be incrementing.

## Actual Behavior
no increment in block height

**Comment by hemz10** [comment]
As mentioned in the [report](https://docs.google.com/spreadsheets/d/1-3DYhOcAjq1GYoBvc8iTN-xhYIOStKDKA6A3eVA0E40/edit#gid=0) since manta testnet is not active closing this issue as deferred
