### ISSUE TITLE
error running subsocial parachain in mainnet and testnet

### ISSUE THREAD

**Issue by sindhu0820** [HugoByte/dive-core#74]
## Overview
error running subsocial parachain in mainnet and testnet

## Steps to Reproduce
1. run subsocial parachain in mainnet

## Expected Behavior
subsocial should start running 

##Actual Behavior
subsocial is not running

## Screenshots
![Screenshot (97)](https://github.com/HugoByte/dive-core/assets/149460495/08ecd3bf-0c1e-4fcd-ba49-516d9f2ea4cb)

**Comment by hemz10** [comment]
blocks are not produced for mainnet

**Comment by sindhu0820** [comment]
for mainnet blocks are producing and
since the testnet is inactive, as mentioned in the report. by considering this closing the issue
