### ISSUE TITLE
error running litmus parachain in testnet

### ISSUE THREAD

**Issue by sindhu0820** [HugoByte/dive-core#84]
## Overview
error running litmus parachain in testnet

## Steps to Reproduce
1. run litmus parachain in testnet
2. ./dive chain kusama -p litmus -n testnet --enclaveName test113

## Expected Behavior
litmus parachain should start running

## Actual Behavior
litmus parachain is not running

## Screenshots
![Screenshot (119)](https://github.com/HugoByte/dive-core/assets/149460495/988beb28-dcc8-4c08-a566-4552e3715e80)
![Screenshot (120)](https://github.com/HugoByte/dive-core/assets/149460495/9c2b14b3-6178-449d-aede-e018eb58c490)

**Comment by hemz10** [comment]
Node started but blocks for parachain are not produced. 
![image](https://github.com/HugoByte/dive-core/assets/96766939/b05ac2cd-0122-4bfb-926e-40f4ad92e84e)

**Comment by hemz10** [comment]
As mentioned in the [report](https://docs.google.com/spreadsheets/d/1-3DYhOcAjq1GYoBvc8iTN-xhYIOStKDKA6A3eVA0E40/edit#gid=0) since litmus testnet is not active closing this issue as deferred
