### ISSUE TITLE
chain is starting when karura parachain is given to polkadot 

### ISSUE THREAD

**Issue by sindhu0820** [HugoByte/dive-core#92]
## Overview
chain is starting when karura parachain is given to polkadot 

## Steps to Reproduce
1. run an chain by giving karura parachain to polkadot relaychain

## Expected Behavior
chain shouldn't start

## Actual Behavior
but chain is running

## Screenshots
![Screenshot (127)](https://github.com/HugoByte/dive-core/assets/149460495/c9dd3d18-17a2-4fa1-8a01-d6c2bccc6a31)

**Comment by hemz10** [comment]
Issue is fixed with valid error message but please correct the output for 'polkadot' 
![image](https://github.com/HugoByte/dive-core/assets/96766939/1f49b759-ba30-42ce-83a6-d83e5cb43f09)

Expected - polkadot
Actual - PolkaDot

**Comment by riyasng12** [comment]
Fixed it! Please re-check it. Thank you! @hemz10

**Comment by hemz10** [comment]
Issue verified and closing it as fixed.
Thanks !
