### ISSUE TITLE
unable to run only parachain using the config file

### ISSUE THREAD

**Issue by sindhu0820** [HugoByte/dive-core#99]
## Overview
unable to run only parachain using the config file

## Steps to Reproduce
1. run an parachain using config file

## Expected Behavior
parachain should start running

## Actual Behavior
parachain is not starting

**Comment by hemz10** [comment]
```json
{
    "chain-type": "testnet",
    "relaychain": {},
  
    "para": [
      {
        "name":"mangata",
        "nodes": [
          {
            "name": "alice",
            "node-type": "validator",
            "prometheus": false
  
          },
          {
            "name": "bob",
            "node-type": "full",
            "prometheus": true
          }
        ]
      }
    ],
    "explorer": true
  }
```

Passing this config to run only parachain fails
![image](https://github.com/HugoByte/dive-core/assets/96766939/d6e626d0-0363-4fb7-a049-401817c173ff)

**Comment by riyasng12** [comment]
@hemz10  Please re-run the command with this updated config:

```
{
  "chain_type": "testnet",
  "relaychain": {
  },

  "parachains": [
    {
      "name":"mangata",
      "nodes": [
        {
          "name": "alice",
          "node_type": "validator",
          "prometheus": false

        },
        {
          "name": "bob",
          "node_type": "full",
          "prometheus": true
        }
      ]
    }
  ],
  "explorer": true
}

**Comment by hemz10** [comment]
Hi @riyasng12 Can you please update the config file in sample json folder as well.

**Comment by riyasng12** [comment]
Hey @hemz10, the config file is updated under the file name **polkadot_config.json**. PLease re-run the command and let us know. Thank you!

**Comment by hemz10** [comment]
Issue verified and closing it as fixed.
Thanks !!
